Repository openshift/networking-console-plugin, pull requests merged in 2024-11, with the labels that each got.

#134 CNV-46603: UDN list & form implementation
  locales/en/plugin__networking-console-plugin.json
  plugin-manifest.ts
  src/templates/index.ts
  src/templates/udns.ts
  src/utils/constants/index.ts
  src/utils/constants/udns.ts
  src/utils/resources/udns/selectors/index.ts
  src/utils/resources/udns/types/index.ts
  src/utils/resources/udns/types/types.ts
  src/utils/resources/udns/utils.ts
  src/views/udns/actions/UDNActions.tsx
  src/views/udns/actions/hooks/useUDNActions.tsx
  src/views/udns/details/tabs/details/UDNLayer2Details.tsx
  src/views/udns/details/tabs/details/UDNLayer3Details.tsx
  src/views/udns/details/tabs/details/UDNLayerDetails.tsx
  src/views/udns/details/tabs/details/UDNTopologyDetails.tsx
  src/views/udns/form/UserDefinedNetworkForm.tsx
  src/views/udns/form/UserDefinedNetworkFormPage.tsx
  src/views/udns/form/components/UDNLayer2Parameters.tsx
  src/views/udns/form/components/UDNLayer3Parameters.tsx
  src/views/udns/form/components/UDNLayerParameters.tsx
  src/views/udns/form/components/UDNSubnets.tsx
  src/views/udns/form/components/UDNTopologySelect.tsx
  src/views/udns/form/utils/constants.ts
  src/views/udns/form/utils/types.ts
  src/views/udns/form/utils/utils.ts
  src/views/udns/list/UserDefinedNetworksList.tsx
  src/views/udns/list/components/UserDefinedNetworkRow.tsx
  src/views/udns/list/hooks/useUDNColumns.tsx
  src/views/udns/manifest.ts
Labels: lgtm, jira/valid-reference, approved

#136 CNV-46603: create udn modal
  locales/en/plugin__networking-console-plugin.json
  src/utils/components/ListEmptyState/ListEmptyState.tsx
  src/views/udns/list/UserDefinedNetworksList.tsx
  src/views/udns/list/components/ProjectSelector.tsx
  src/views/udns/list/components/UserDefinedNetworkCreateForm.tsx
  src/views/udns/list/components/UserDefinedNetworkCreateModal.tsx
  src/views/udns/list/components/utils.ts
  src/views/udns/list/constants.ts
  src/views/udns/list/hooks/useProjects.tsx
Labels: lgtm, jira/valid-reference, approved

#140 OCPBUGS-44396: OCPBUGS-44680: upgrade packages for cve
  yarn.lock
Labels: lgtm, jira/valid-reference, jira/valid-bug, approved

#133 CNV-46603: create udn with project
  locales/en/plugin__networking-console-plugin.json
  plugin-manifest.ts
  src/templates/udns.ts
  src/utils/flags/consts.ts
  src/utils/flags/index.ts
  src/utils/flags/manifest.ts
  src/utils/flags/useUDNEnabledFlag.ts
  src/utils/models/index.ts
  src/utils/resources/udns/utils.ts
  src/views/createprojectmodal/CreateProjectModal.scss
  src/views/createprojectmodal/CreateProjectModal.tsx
  src/views/createprojectmodal/components/CreateProjectModalForm.tsx
  src/views/createprojectmodal/components/DetailsProjectTab.tsx
  src/views/createprojectmodal/components/NetworkTab.tsx
  src/views/createprojectmodal/components/ProjectNamePopover.tsx
  src/views/createprojectmodal/constants.ts
  src/views/createprojectmodal/manifest.ts
  src/views/createprojectmodal/types.ts
  src/views/createprojectmodal/useClusterUDN.ts
  src/views/udns/actions/hooks/useUDNActions.tsx
  src/views/udns/form/UserDefinedNetworkForm.tsx
  src/views/udns/form/utils/constants.ts
  src/views/udns/form/utils/utils.ts
  src/views/udns/list/UserDefinedNetworksList.tsx
  src/views/udns/list/components/UserDefinedNetworkCreateModal.tsx
  src/views/udns/list/components/UserDefinedNetworkRow.tsx
Labels: lgtm, jira/valid-reference, approved

#137 CNV-46603: add CUDN kind
  README.md
  locales/en/plugin__networking-console-plugin.json
  src/templates/udns.ts
  src/utils/components/MatchExpression/Expression.tsx
  src/utils/components/MatchExpression/MatchExpression.tsx
  src/utils/components/Select/Select.tsx
  src/utils/constants/udns.ts
  src/utils/resources/udns/selectors/index.ts
  src/utils/resources/udns/types/types.ts
  src/views/createprojectmodal/components/DetailsProjectTab.tsx
  src/views/createprojectmodal/components/NetworkTab.tsx
  src/views/services/details/tabs/pods/components/PodTraffic.tsx
  src/views/udns/actions/UDNActions.tsx
  src/views/udns/actions/hooks/useUDNActions.tsx
  src/views/udns/details/tabs/details/UDNLayer2Details.tsx
  src/views/udns/details/tabs/details/UDNLayer3Details.tsx
  src/views/udns/details/tabs/details/UDNLayerDetails.tsx
  src/views/udns/details/tabs/details/UDNTopologyDetails.tsx
  src/views/udns/form/UserDefinedNetworkForm.tsx
  src/views/udns/form/UserDefinedNetworkFormPage.tsx
  src/views/udns/form/components/CUDNNamespaceSelector.tsx
  src/views/udns/form/components/UDNLayer2Parameters.tsx
  src/views/udns/form/components/UDNLayer3Parameters.tsx
  src/views/udns/form/components/UDNSubnets.tsx
  src/views/udns/form/components/UDNTopologySelect.tsx
  src/views/udns/form/utils/constants.ts
  src/views/udns/form/utils/types.ts
  src/views/udns/form/utils/utils.ts
  src/views/udns/list/UserDefinedNetworksList.tsx
  src/views/udns/list/components/UserDefinedNetworkRow.tsx
  src/views/udns/list/hooks/useUDNFilters.tsx
  src/views/udns/manifest.ts
Labels: lgtm, jira/valid-reference, ok-to-test, approved

#143 CNV-52127: remove `t` calls that are not within components
  src/utils/constants/index.ts
  src/utils/constants/nads.ts
  src/utils/constants/udns.ts
  src/utils/models/index.ts
  src/views/nads/form/NetworkAttachmentDefinitionFormPage.tsx
  src/views/udns/form/UserDefinedNetworkFormPage.tsx
Labels: lgtm, jira/valid-reference, approved

#144 [release-4.18] CNV-52128: remove t calls that are not within components
  src/utils/constants/index.ts
  src/utils/constants/nads.ts
  src/utils/constants/udns.ts
  src/utils/models/index.ts
  src/views/nads/form/NetworkAttachmentDefinitionFormPage.tsx
  src/views/udns/form/UserDefinedNetworkFormPage.tsx
Labels: lgtm, jira/valid-reference, approved
