Repository openshift/networking-console-plugin, pull requests merged in 2024-10, with the labels that each got.

#124 OCPBUGS-41969: OCPBUGS-42352: add service weight
  locales/en/plugin__networking-console-plugin.json
  src/views/routes/form/AlternateService.tsx
  src/views/routes/form/RouteForm.tsx
  src/views/routes/form/ServiceSelector.tsx
  src/views/routes/form/Targetport.tsx
  src/views/routes/form/constants.ts
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#126 OCPBUGS-42354: hide routes metrics non-admin users
  src/views/routes/details/hooks/useRouteTabs.ts
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#127 CNV-49305: fix for virt perspective
  src/views/nads/manifest.ts
  src/views/networkpolicies/manifest.ts
  src/views/routes/manifest.ts
Labels: lgtm, jira/valid-reference, approved

#130 OCPBUGS-43034: Routes list sort by status
  src/views/routes/list/hooks/useRouteColumns.ts
  src/views/routes/list/utils/utils.ts
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#132 OCPBUGS-43034: Add Route Filter in route list
  src/utils/constants/routes.ts
  src/views/routes/list/RoutesList.tsx
  src/views/routes/list/hooks/useRouteFilters.ts
  src/views/routes/list/utils/utils.ts
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#135 OCPBUGS-43873 Routes list page shows correct status and location
  src/views/routes/list/RoutesList.tsx
Labels: lgtm, approved
