Repository openshift/networking-console-plugin, pull requests merged in 2024-12, with the labels that each got.

#147 run kubevirt-plugin using start-console
  start-console.sh
  webpack.config.ts
Labels: lgtm, approved

#145 CNV-46603: Cluster UDN modal creation
  locales/en/plugin__networking-console-plugin.json
  src/utils/components/MatchLabels/MatchLabels.tsx
  src/views/udns/form/components/CUDNNamespaceSelector.tsx
  src/views/udns/list/UserDefinedNetworksList.tsx
  src/views/udns/list/components/ClusterUDNNamespaceSelector.tsx
  src/views/udns/list/components/ProjectSelector.tsx
  src/views/udns/list/components/SelectProject.tsx
  src/views/udns/list/components/UserDefinedNetworkCreateForm.tsx
  src/views/udns/list/components/UserDefinedNetworkCreateModal.tsx
  src/views/udns/list/components/constants.ts
  src/views/udns/list/components/utils.ts
Labels: lgtm, jira/valid-reference, approved

#146 CNV-46603: Create project modal with ClusterUDN creation
  locales/en/plugin__networking-console-plugin.json
  src/utils/components/Loading/InlineLoading.tsx
  src/utils/components/Loading/Loading.tsx
  src/views/createprojectmodal/CreateProjectModal.tsx
  src/views/createprojectmodal/components/NetworkTab.tsx
  src/views/createprojectmodal/components/SelectClusterUDN.tsx
  src/views/createprojectmodal/constants.ts
  src/views/createprojectmodal/types.ts
Labels: lgtm, jira/valid-reference, approved

#142 CNV-46603: search project by name and fix select height
  locales/en/plugin__networking-console-plugin.json
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
  src/utils/components/SelectTypeahead/Toggle.tsx
  src/utils/components/SelectTypeahead/utils.ts
  src/views/udns/list/components/ProjectSelector.tsx
  src/views/udns/list/components/SelectProject.tsx
  src/views/udns/list/components/UserDefinedNetworkCreateModal.tsx
  src/views/udns/list/components/userdefinednetworkcreatemodal.scss
Labels: lgtm, jira/valid-reference, approved

#149 Backport udn to 4.18
  README.md
  locales/en/plugin__networking-console-plugin.json
  src/templates/udns.ts
  src/utils/components/Loading/InlineLoading.tsx
  src/utils/components/Loading/Loading.tsx
  src/utils/components/MatchExpression/Expression.tsx
  src/utils/components/MatchExpression/MatchExpression.tsx
  src/utils/components/MatchLabels/MatchLabels.tsx
  src/utils/components/Select/Select.tsx
  src/utils/components/SelectTypeahead/SelectTypeahead.tsx
  src/utils/components/SelectTypeahead/Toggle.tsx
  src/utils/components/SelectTypeahead/utils.ts
  src/utils/resources/udns/selectors/index.ts
  src/utils/resources/udns/types/types.ts
  src/views/createprojectmodal/CreateProjectModal.tsx
  src/views/createprojectmodal/components/DetailsProjectTab.tsx
  src/views/createprojectmodal/components/NetworkTab.tsx
  src/views/createprojectmodal/components/SelectClusterUDN.tsx
  src/views/createprojectmodal/constants.ts
  src/views/createprojectmodal/types.ts
  src/views/services/details/tabs/pods/components/PodTraffic.tsx
  src/views/udns/actions/UDNActions.tsx
  src/views/udns/actions/hooks/useUDNActions.tsx
  src/views/udns/details/tabs/details/UDNLayer2Details.tsx
  src/views/udns/details/tabs/details/UDNLayer3Details.tsx
  src/views/udns/details/tabs/details/UDNLayerDetails.tsx
  src/views/udns/details/tabs/details/UDNTopologyDetails.tsx
  src/views/udns/form/UserDefinedNetworkForm.tsx
  src/views/udns/form/UserDefinedNetworkFormPage.tsx
  src/views/udns/form/components/CUDNNamespaceSelector.tsx
  src/views/udns/form/components/UDNLayer2Parameters.tsx
  src/views/udns/form/components/UDNLayer3Parameters.tsx
  src/views/udns/form/components/UDNSubnets.tsx
  src/views/udns/form/components/UDNTopologySelect.tsx
  src/views/udns/form/utils/constants.ts
  src/views/udns/form/utils/types.ts
  src/views/udns/form/utils/utils.ts
  src/views/udns/list/UserDefinedNetworksList.tsx
  src/views/udns/list/components/ClusterUDNNamespaceSelector.tsx
  src/views/udns/list/components/ProjectSelector.tsx
  src/views/udns/list/components/SelectProject.tsx
  src/views/udns/list/components/UserDefinedNetworkCreateForm.tsx
  src/views/udns/list/components/UserDefinedNetworkCreateModal.tsx
  src/views/udns/list/components/UserDefinedNetworkRow.tsx
  src/views/udns/list/components/constants.ts
  src/views/udns/list/components/userdefinednetworkcreatemodal.scss
  src/views/udns/list/components/utils.ts
  src/views/udns/list/hooks/useUDNFilters.tsx
  src/views/udns/manifest.ts
Labels: lgtm, approved

#150 CNV-46603: select projects with multitypeahead
  src/utils/components/SelectMultiTypeahead/utils.ts
  src/utils/resources/udns/constants.ts
  src/views/createprojectmodal/CreateProjectModal.tsx
  src/views/createprojectmodal/utils.ts
  src/views/udns/list/components/ClusterUDNNamespaceSelector.tsx
  src/views/udns/list/components/utils.ts
Labels: lgtm, jira/valid-reference, approved

#151 OCPBUGS-45050: UI crash accessing a Service in pending state
  src/views/services/details/tabs/details/ServiceAddress.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, approved

#153 CNV-50554: fix create button position
  locales/en/plugin__networking-console-plugin.json
  src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
  src/views/networkpolicies/list/NetworkPolicyList.tsx
  src/views/networkpolicies/list/NetworkPolicyPage.tsx
Labels: lgtm, jira/valid-reference, approved

#154 OCPBUGS-46557: fix project displayName and description
  src/views/createprojectmodal/components/DetailsProjectTab.tsx
  src/views/createprojectmodal/constants.ts
  src/views/createprojectmodal/types.ts
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#152 OCPBUGS-46553: fix ports as number instead of strings
  src/utils/models/network-policy.ts
  src/views/networkpolicies/new/components/NetworkPolicyFormPorts.tsx
Labels: lgtm, approved
