Repository openshift/networking-console-plugin, pull requests merged in 2024-09, with the labels that each got.

#59 OCPBUGS-39249: fix Sort all resources list
  src/utils/utils/sorting.ts
  src/views/ingresses/list/hooks/useIngressColumns.tsx
  src/views/ingresses/list/utils/utils.ts
  src/views/nads/list/hooks/useNADsColumns.tsx
  src/views/networkpolicies/list/hooks/useNetworkPolicyColumn.tsx
  src/views/routes/list/components/RouteRow.tsx
  src/views/routes/list/hooks/useRouteColumns.ts
  src/views/services/list/hooks/useServiceColumn.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#68 CNV-47530: fix typehead select on multi policy
  src/utils/components/SelectMultiTypeahead/Toggle.tsx
Labels: lgtm, jira/valid-reference, approved

#67 CNV-47529: Fix doc link MultiNetworkPolicy
  src/views/nads/list/NetworkAttachmentDefinitionList.tsx
Labels: lgtm, jira/valid-reference, approved

#71 CNV-48187: Create MultiNetworkPolicy instead of NetworkPolicy
  src/utils/models/network-policy.ts
  src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
  src/views/networkpolicies/new/NetworkPolicyForm.tsx
  src/views/networkpolicies/new/NetworkPolicyFormSections.tsx
Labels: lgtm, jira/valid-reference, approved

#74 OCPBUGS-41578: fix router link
  src/views/routes/list/components/RouteRow.tsx
Labels: lgtm, jira/severity-important, jira/valid-reference, jira/valid-bug, approved

#78 OCPBUGS-41618: switch key with label
  src/utils/components/DetailsItem/LabelList.tsx
Labels: lgtm, jira/severity-important, jira/valid-reference, jira/valid-bug, approved

#79 OCPBUGS-39084: normal user have to use projects no namespaces
  src/views/networkpolicies/new/components/NetworkPolicySelectorPreview/components/hooks/useNetworkPolicyPodPreviewData.ts
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#72 OCPBUGS-41501: Add status box for error handling
  locales/en/plugin__networking-console-plugin.json
  src/custom.d.ts
  src/utils/components/ListEmptyState/ListEmptyState.tsx
  src/utils/components/ListEmptyState/ListErrorState.tsx
  src/utils/components/ListEmptyState/ListSkeleton.tsx
  src/utils/components/ListEmptyState/list-error-state.scss
  src/utils/components/ListEmptyState/restricted-sign.svg
  src/views/ingresses/list/IngressesList.tsx
  src/views/nads/list/NetworkAttachmentDefinitionList.tsx
  src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
  src/views/networkpolicies/list/NetworkPolicyList.tsx
  src/views/routes/list/RoutesList.tsx
  src/views/services/list/ServiceList.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-low, approved

#76 OCPBUGS-41590: fix networkpolicy pagination
  src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
  src/views/networkpolicies/list/NetworkPolicyList.tsx
Labels: lgtm, jira/severity-important, jira/valid-reference, jira/valid-bug, approved

#85 OCPBUGS-41697: OCPBUGS-41698: Add annotation field in ingress details page
  src/views/ingresses/details/tabs/details/components/IngressDetailsSection/IngressDetailsSection.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#86 OCPBUGS-41692: fix remove function
  src/views/routes/form/AlternateService.tsx
  src/views/routes/form/AlternateServicesSection.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#90 OCPBUGS-41699: OCPBUGS-41695: fix clear fileupload not working
  src/views/routes/form/TLSTermination.tsx
Labels: lgtm, jira/severity-important, jira/valid-reference, jira/valid-bug, approved

#84 CNV-48188: Fix networkpolicy list
  src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
  src/views/networkpolicies/list/NetworkPolicyList.tsx
  src/views/networkpolicies/list/NetworkPolicyPage.tsx
Labels: lgtm, jira/valid-reference, approved

#89 OCPBUGS-41605: Fix lastnamespacepath with actual namespace
  src/views/networkpolicies/list/EnableMultiPage.tsx
  src/views/networkpolicies/list/NetworkPolicyPage.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#87 OCPBUGS-41765: fix ingress namespace in details page
  src/views/ingresses/details/tabs/details/components/IngressDetailsSection/IngressDetailsSection.tsx
Labels: lgtm, jira/severity-important, jira/valid-reference, jira/valid-bug, approved

#88 OCPBUGS-41693: Add Error page for not found resources and other errors
  locales/en/plugin__networking-console-plugin.json
  src/utils/components/ErrorPage/ErrorPage.tsx
  src/utils/components/ErrorPage/error-page.scss
  src/utils/components/StatusBox/StatusBox.tsx
  src/views/ingresses/details/IngressDetailsPage.tsx
  src/views/networkpolicies/details/NetworkPolicyDetailsPage.tsx
  src/views/routes/details/RouteDetailsPage.tsx
  src/views/services/details/ServiceDetailsPage.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-low, approved

#103 OCPBUGS-41699: Add destination ca cert
  src/views/routes/form/TLSTermination.tsx
  src/views/routes/form/constants.ts
  src/views/routes/form/utils.ts
Labels: lgtm, jira/severity-important, jira/valid-reference, jira/valid-bug, approved

#107 CNV-47528: Fix key value in selector
  locales/en/plugin__networking-console-plugin.json
  src/utils/components/LabelSelectorEditor/LabelSelectorEditor.tsx
Labels: lgtm, jira/valid-reference, approved

#108 OCPBUGS-42141: fix pagination during sorting
  src/utils/utils/sorting.ts
  src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
  src/views/networkpolicies/list/NetworkPolicyList.tsx
  src/views/networkpolicies/list/hooks/useNetworkPolicyColumn.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, approved

#113 Revert IPAM (subnets input)
  locales/en/plugin__networking-console-plugin.json
  src/views/nads/form/components/NetworkTypeParameters/components/OVNK8sSecondaryLocalnetParameters/OVNK8sSecondaryLocalnetParameters.tsx
  src/views/nads/form/components/NetworkTypeParameters/utils/constants.ts
Labels: lgtm, approved

#118 CNV-48190: move title networkpolicies above tabs
  src/utils/components/ListEmptyState/ListEmptyState.tsx
  src/utils/components/ListEmptyState/ListErrorState.tsx
  src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
  src/views/networkpolicies/list/NetworkPolicyList.tsx
  src/views/networkpolicies/list/NetworkPolicyPage.tsx
Labels: lgtm, jira/valid-reference, approved

#119 OCPBUGS-42311: Route edit form
  locales/en/plugin__networking-console-plugin.json
  src/views/routes/actions/hooks/useRouteActions.ts
  src/views/routes/details/EditRoute.tsx
  src/views/routes/form/RouteForm.tsx
  src/views/routes/form/RouteFormActions.tsx
  src/views/routes/form/RouteFormPage.tsx
  src/views/routes/form/useIsCreationForm.tsx
  src/views/routes/form/utils.ts
  src/views/routes/manifest.ts
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#112 OCPBUGS-42134: fix html in translations
  locales/en/plugin__networking-console-plugin.json
  src/views/routes/form/TLSTermination.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-low, approved

#105 OCPBUGS-39249: fix sorting on lists
  src/utils/utils/sorting.ts
  src/views/ingresses/list/hooks/useIngressColumns.tsx
  src/views/networkpolicies/list/hooks/useNetworkPolicyColumn.tsx
  src/views/routes/list/hooks/useRouteColumns.ts
  src/views/routes/list/utils/utils.ts
  src/views/services/list/components/ServiceRow.tsx
  src/views/services/list/hooks/useServiceColumn.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved
