Repository openshift/networking-console-plugin, pull requests merged in 2024-08, with the labels that each got.

#47 OCPBUGS-38923: Replace hardcoded strings with internationalized version
  src/views/ingresses/manifest.ts
  src/views/nads/manifest.ts
  src/views/networkpolicies/manifest.ts
  src/views/routes/manifest.ts
  src/views/services/manifest.ts
Labels: lgtm, jira/valid-reference, jira/valid-bug, approved

#49 Fix kubevirt dynamic flag
  src/utils/flags/consts.ts
  src/views/nads/manifest.ts
Labels: lgtm, approved

#50 fix create button from /~new to /~new/form to show the creation form
  src/views/routes/list/RoutesList.tsx
Labels: lgtm, approved

#54 OCPBUGS-39083: fix switching namespaces in policies
  src/views/networkpolicies/list/NetworkPolicyPage.tsx
  src/views/networkpolicies/list/utils.ts
Labels: lgtm, jira/severity-important, jira/valid-reference, jira/valid-bug, approved

#57 OCPBUGS-39247: fix docs links
  src/views/ingresses/list/IngressesList.tsx
  src/views/networkpolicies/list/NetworkPolicyList.tsx
  src/views/routes/list/RoutesList.tsx
  src/views/services/list/ServiceList.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#58 OCPBUGS-39248: fix pod selector path
  src/utils/components/PodSelectorModal/PodSelectorModal.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#55 OCPBUGS-39084: fix pod preview error
  .stylelintrc.yaml
  package.json
  src/views/networkpolicies/new/components/NetworkPolicySelectorPreview/components/NetworkPolicyPodsPreview.tsx
  src/views/networkpolicies/new/components/NetworkPolicySelectorPreview/components/hooks/useNetworkPolicyPodPreviewData.ts
  src/views/networkpolicies/new/components/NetworkPolicySelectorPreview/components/tree-view.css
  yarn.lock
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#61 OCPBUGS-39250: fix small routes bugs
  src/utils/resources/shared.ts
  src/views/routes/form/RouteForm.tsx
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#51 Use rhel9 base image in Dockerfile
  Dockerfile
Labels: lgtm, approved
