Repository openshift/networking-console-plugin, pull requests merged in 2025-09, with the labels that each got.

#269 CNV-68676: fix wizard cancel button
  src/views/vmnetworks/actions/components/EditProjectMappingModal.tsx
  src/views/vmnetworks/constants.ts
  src/views/vmnetworks/details/components/VMNetworkTitle.tsx
  src/views/vmnetworks/form/VMNetworkNewForm.tsx
  src/views/vmnetworks/list/VMNetworkList.tsx
  src/views/vmnetworks/list/components/VMNetworkRow.tsx
  src/views/vmnetworks/manifest.ts
Labels: lgtm, jira/valid-reference, approved

#275 OCPBUGS-61531: show VM network menu only on admin
  src/views/vmnetworks/manifest.ts
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-moderate, approved

#273 New OWNERS list
  OWNERS
Labels: approved
