Repository openshift/networking-console-plugin, pull requests merged in 2025-02, with the labels that each got.

#206 Fix nads with no label
  src/utils/resources/nads/helpers.ts
Labels: lgtm, approved

#210 CNV-56076: create cudn from empty state
  src/utils/components/ListEmptyState/ListEmptyState.tsx
  src/views/udns/list/UserDefinedNetworksList.tsx
Labels: lgtm, jira/valid-reference, approved

#212 CNV-56336: fix ipam lifecycle with new spec
  src/utils/resources/udns/types/types.ts
  src/views/createprojectmodal/constants.ts
  src/views/udns/form/components/UDNLayer2Parameters.tsx
  src/views/udns/form/utils/utils.ts
  src/views/udns/list/components/utils.ts
Labels: lgtm, jira/valid-reference, approved

#214 OCPBUGS-42135: Update documentation links
  src/utils/constants/documentation.tsx
  src/views/ingresses/list/IngressesList.tsx
  src/views/nads/list/NetworkAttachmentDefinitionList.tsx
  src/views/networkpolicies/list/MultiNetworkPolicyList.tsx
  src/views/networkpolicies/list/NetworkPolicyList.tsx
  src/views/routes/list/RoutesList.tsx
  src/views/services/list/ServiceList.tsx
  src/views/udns/list/UserDefinedNetworksList.tsx
Labels: lgtm, jira/valid-reference, ok-to-test, jira/valid-bug, jira/severity-moderate, approved

#217 CNV-56236: fix cudn modal form titles
  src/views/udns/list/components/ClusterUDNNamespaceSelector.tsx
Labels: lgtm, jira/valid-reference, approved

#216 OCPBUGS-41964: No default path in the route creation form
  src/views/routes/form/utils.ts
Labels: lgtm, jira/valid-reference, jira/valid-bug, jira/severity-low, approved

#218 CNV-56436: show ipam lifecycle correctly with new spec
  locales/en/plugin__networking-console-plugin.json
  src/views/udns/details/tabs/details/UDNLayer2Details.tsx
Labels: lgtm, jira/valid-reference, approved
