Repository openshift/networking-console-plugin, pull requests merged in 2025-04, with the labels that each got.

#228 CNV-58647: update PatternFly Modal to new version
  src/styles/modal-action.scss
  src/utils/components/ConfirmModal/ConfirmModal.tsx
  src/utils/components/CopyToClipboard/CopyToClipboard.tsx
  src/utils/components/DetailsItem/DetailsItem.tsx
  src/utils/components/LabelSelectorEditor/LabelSelectorEditor.tsx
  src/utils/components/ListEmptyState/ListErrorState.tsx
  src/utils/components/MatchExpression/Expression.tsx
  src/utils/components/MatchExpression/MatchExpression.tsx
  src/utils/components/PodSelectorModal/PodSelectorModal.tsx
  src/utils/components/SyncedEditor/SyncedEditor.tsx
  src/views/createprojectmodal/CreateProjectModal.tsx
  src/views/nads/list/components/NADListEmpty/NADListEmpty.tsx
  src/views/networkpolicies/new/NetworkPolicyConditionalSelector.tsx
  src/views/networkpolicies/new/NetworkPolicyPeerIPBlock.tsx
  src/views/networkpolicies/new/components/NetworkPolicyFormActionButtons.tsx
  src/views/networkpolicies/new/components/NetworkPolicyFormEgress.tsx
  src/views/networkpolicies/new/components/NetworkPolicyFormIngress.tsx
  src/views/networkpolicies/new/components/NetworkPolicyFormPodSelector.tsx
  src/views/networkpolicies/new/components/NetworkPolicyFormPorts.tsx
  src/views/networkpolicies/new/components/NetworkPolicyFormSDNAlert.tsx
  src/views/networkpolicies/new/components/NetworkPolicyRuleConfigPanel/components/NetworkPolicyRuleConfigPanelRulePeer.tsx
  src/views/routes/details/components/tabs/detailsTab/components/RouteDetailsSection/CustomRouteHelp.tsx
  src/views/routes/details/components/tabs/detailsTab/components/RouteDetailsSection/DetailsSectionLeftColumn.tsx
  src/views/routes/details/components/tabs/detailsTab/components/TLSSettingsSection/TLSSettings.tsx
  src/views/routes/form/AlternateService.tsx
  src/views/routes/form/AlternateServicesSection.tsx
  src/views/routes/form/RouteFormActions.tsx
  src/views/services/details/tabs/details/ServiceDetails.tsx
  src/views/services/details/tabs/pods/components/PodStatus.tsx
  src/views/udns/details/tabs/details/UDNLayerDetails.tsx
  src/views/udns/form/components/UDNSubnets.tsx
  src/views/udns/list/components/UserDefinedNetworkCreateModal.tsx
Labels: lgtm, jira/valid-reference, approved

#231 CNV-59853: remove co-m-table-grid and dropdown-kebab-pf classes
  src/views/ingresses/details/tabs/details/components/IngressRulesSection/IngressRulesSection.tsx
  src/views/ingresses/details/tabs/details/components/IngressRulesSection/RulesHeader.tsx
  src/views/ingresses/details/tabs/details/components/IngressRulesSection/RulesRow.tsx
  src/views/ingresses/details/tabs/details/components/IngressRulesSection/RulesRows.tsx
  src/views/nads/list/components/NADsRow/NADsRow.tsx
  src/views/nads/list/hooks/useNADsColumns.tsx
  src/views/networkpolicies/details/tabs/details/components/NetworkPolicyDetailsEgress.tsx
  src/views/networkpolicies/details/tabs/details/components/NetworkPolicyDetailsRow/NetworkPolicyDetailsRow.tsx
  src/views/networkpolicies/list/components/NetworkPolicyRow.tsx
  src/views/networkpolicies/list/hooks/useNetworkPolicyColumn.tsx
  src/views/routes/details/components/tabs/detailsTab/components/RouteIngressStatusSection/ConditionRow.tsx
  src/views/routes/details/components/tabs/detailsTab/components/RouteIngressStatusSection/Conditions.tsx
  src/views/services/list/hooks/useServiceColumn.tsx
  src/views/udns/list/components/UserDefinedNetworkRow.tsx
  src/views/udns/list/hooks/useUDNColumns.tsx
Labels: lgtm, jira/valid-reference, approved

#229 Upload i18n translations scripts
  i18n-scripts/export-pos.sh
  i18n-scripts/i18n-to-po.js
  i18n-scripts/languages.sh
  i18n-scripts/memsource-download.sh
  i18n-scripts/memsource-upload.sh
  i18n-scripts/po-to-i18n.js
  i18next-parser.config.js
  locales/es/plugin__networking-console-plugin.json
  locales/fr/plugin__networking-console-plugin.json
  locales/ja/plugin__networking-console-plugin.json
  locales/ko/plugin__networking-console-plugin.json
  locales/zh/plugin__networking-console-plugin.json
  package.json
  yarn.lock
Labels: lgtm, approved

#236 OCPBUGS-49395: adding translations
  i18n-scripts/po-to-i18n.js
  locales/es/plugin__networking-console-plugin.json
  locales/fr/plugin__networking-console-plugin.json
  locales/ja/plugin__networking-console-plugin.json
  locales/ko/plugin__networking-console-plugin.json
  locales/zh/plugin__networking-console-plugin.json
Labels: lgtm, jira/valid-reference, ok-to-test, jira/valid-bug, jira/severity-low, approved

#233 CNV-60065: fix cudn input name
  src/views/udns/list/components/UserDefinedNetworkCreateForm.tsx
Labels: lgtm, jira/valid-reference, approved

#234 [release-4.18] Add translations scripts
  i18n-scripts/export-pos.sh
  i18n-scripts/i18n-to-po.js
  i18n-scripts/languages.sh
  i18n-scripts/memsource-download.sh
  i18n-scripts/memsource-upload.sh
  i18n-scripts/po-to-i18n.js
  i18next-parser.config.js
  locales/es/plugin__networking-console-plugin.json
  locales/fr/plugin__networking-console-plugin.json
  locales/ja/plugin__networking-console-plugin.json
  locales/ko/plugin__networking-console-plugin.json
  locales/zh/plugin__networking-console-plugin.json
  package.json
  yarn.lock
Labels: lgtm, ok-to-test, approved

#235 [release-4.17] Add translations scripts
  i18n-scripts/export-pos.sh
  i18n-scripts/i18n-to-po.js
  i18n-scripts/languages.sh
  i18n-scripts/memsource-download.sh
  i18n-scripts/memsource-upload.sh
  i18n-scripts/po-to-i18n.js
  i18next-parser.config.js
  locales/es/plugin__networking-console-plugin.json
  locales/fr/plugin__networking-console-plugin.json
  locales/ja/plugin__networking-console-plugin.json
  locales/ko/plugin__networking-console-plugin.json
  locales/zh/plugin__networking-console-plugin.json
  package.json
  yarn.lock
Labels: lgtm, ok-to-test, approved
